Repository DeveloperAcademy-POSTECH/mc3-team6-nspu, pull requests merged in 2023-07, with the labels that each got.

#4 Projectinit
  OrrNyan/OrrNyan Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  OrrNyan/OrrNyan Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  OrrNyan/OrrNyan Watch App/Assets.xcassets/Contents.json
  OrrNyan/OrrNyan Watch App/ContentView.swift
  OrrNyan/OrrNyan Watch App/OrrNyanApp.swift
  OrrNyan/OrrNyan Watch App/Preview Content/Preview Assets.xcassets/Contents.json
  OrrNyan/OrrNyan Watch App/StairTest.swift
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  OrrNyan/OrrNyan/Assets.xcassets/AccentColor.colorset/Contents.json
  OrrNyan/OrrNyan/Assets.xcassets/AppIcon.appiconset/Contents.json
  OrrNyan/OrrNyan/Assets.xcassets/Contents.json
  OrrNyan/OrrNyan/ContentView.swift
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/Preview Content/Preview Assets.xcassets/Contents.json
Labels: chore

#6 Chore/#05
  OrrNyan/OrrNyan Watch App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  OrrNyan/OrrNyan Watch App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  OrrNyan/OrrNyan Watch App/Resources/Assets.xcassets/Contents.json
  OrrNyan/OrrNyan Watch App/UI/Screen/ContentView.swift
  OrrNyan/OrrNyan Watch App/Utilities/StairTest.swift
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Models/UserModel.swift
  OrrNyan/OrrNyan/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Contents.json
  OrrNyan/OrrNyan/UI/Components/HeaderView.swift
  OrrNyan/OrrNyan/UI/Screen/ContentView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
  OrrNyan/OrrNyan/Utilities/Extension+Color.swift
Labels: chore

#11 [Chore] #10 - add Models
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Models/AppPush.swift
  OrrNyan/OrrNyan/Models/StageInfo.swift
  OrrNyan/OrrNyan/Models/User.swift
  OrrNyan/OrrNyan/Models/UserBadge.swift
  OrrNyan/OrrNyan/Models/UserFloor.swift
  OrrNyan/OrrNyan/Models/UserModel.swift
  OrrNyan/OrrNyan/Models/UserStage.swift
Labels: chore

#13 [FEAT]: #12 - Added CreateNameVIew
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  OrrNyan/OrrNyan/UI/Components/CatButtonStyle.swift
  OrrNyan/OrrNyan/UI/Components/LottieView.swift
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
Labels: feat

#14 [Feat] #08 -firstCat.json 추가
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Resources/firstCat.json
Labels: feat

#15 [Feat] #08 - add firebase package
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  OrrNyan/OrrNyan/GoogleService-Info.plist
  OrrNyan/OrrNyan/Info.plist
  OrrNyan/OrrNyan/OrrNyan.entitlements
Labels: feat

#21 [REMOVE] #09 - ACarousel 폴더 수정
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/UI/Components/ACarouselAutoScroll.swift
  OrrNyan/OrrNyan/UI/Components/ACarouselViewModel.swift
  OrrNyan/OrrNyan/UI/Components/View+ReceiveTimer.swift
Labels: remove

#23 Feat/#08 - Firebase create UserFloor
  OrrNyan/OrrNyan/Models/User.swift
  OrrNyan/OrrNyan/Models/UserFloor.swift
  OrrNyan/OrrNyan/UI/Screen/ContentView.swift
  OrrNyan/OrrNyan/UI/Screen/LoginView.swift
  OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
Labels: feat

#30 [Feat] - LoginView_malty 작업 완료
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Image/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Image/ImgLogoApple.imageset/Apple.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Image/ImgLogoApple.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Image/ImgLogoGoogle.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Image/ImgLogoGoogle.imageset/Google.png
  OrrNyan/OrrNyan/UI/Screen/LoginView_malty.swift
Labels: feat

#31 Style/#20
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Black/Black100.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Black/Black200.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Black/Black300.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Black/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Pink/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Pink/Pink300.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Purple/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Purple/Purple100.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Purple/Purple200.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Purple/Purple300.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/White/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/White/White100.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/White/White200.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/White/White300.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg01.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg01.imageset/StageBg01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg02.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg02.imageset/StageBg02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg03.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg03.imageset/StageBg03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_01.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_01.imageset/StageEm01_01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_02.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_02.imageset/StageEm01_02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_03.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_03.imageset/StageEm01_03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_04.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_04.imageset/StageEm01_04.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_01.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_01.imageset/StageEm02_01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_02.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_02.imageset/StageEm02_02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_03.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_03.imageset/StageEm02_03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_01.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_01.imageset/StageEm03_01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_02.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_02.imageset/StageEm03_02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_03.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_03.imageset/StageEm03_03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt01.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt01.imageset/StageSt01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt02.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt02.imageset/StageSt02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt03.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt03.imageset/StageSt03.png
  OrrNyan/OrrNyan/Resources/Colors/ColorManager.swift
Labels: style

#34 Feat/#33
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Resources/Assets.xcassets/upCat.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/upCat.imageset/upCat.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/이/Contents.json
  OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/UpCat.swift
Labels: feat

#29 Feat/#09 - grayScale 적용
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Models/StageItem.swift
  OrrNyan/OrrNyan/Models/UserFloor.swift
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/UI/Components/ACarouselViewModel.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainTopView.swift
  OrrNyan/OrrNyan/UI/Screen/StageView.swift
  OrrNyan/OrrNyan/UI/Screen/TestTransitionView.swift
Labels: feat

#35 [Feat] #12 - CreateNameView Hifi 적용
  OrrNyan/OrrNyan/UI/Components/CatButtonStyle.swift
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
Labels: feat

#38 Feat/#37 - StageView to MainView transition
  OrrNyan/OrrNyan/Models/StageItem.swift
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt01.imageset/StageSt01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt02.imageset/StageSt02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt03.imageset/StageSt03.png
  OrrNyan/OrrNyan/UI/Components/ACarouselViewModel.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
  OrrNyan/OrrNyan/UI/Screen/StageView.swift
Labels: feat

#36 Feat/#08 - Firebase UserFloor CRUD
  OrrNyan/OrrNyan/UI/Screen/LoginView.swift
  OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
  OrrNyan/OrrNyan/Utilities/Firebase/SignInWithApple.swift
  OrrNyan/OrrNyan/Utilities/Firebase/SignInWithGoogle.swift
Labels: feat

#42 [Chore] #39 - LoginView -> CreateNameView 합치기
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/LoginView_malty.swift
Labels: chore

#41 [Fix] #08 - AppleLogin 오류 수정
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/UI/Screen/LoginView.swift
  OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
  OrrNyan/OrrNyan/Utilities/Firebase/SignInWithApple.swift
  OrrNyan/OrrNyan/Utilities/Firebase/SignInWithGoogle.swift
Labels: fix

#46 [Style] #45 - Lottie 추가 / test Lottie 삭제
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Resources/Lottie/LottieCreateNameView.json
  OrrNyan/OrrNyan/Resources/Lottie/LottieLoginView.json
  OrrNyan/OrrNyan/Resources/Lottie/LottieMainViewSit.json
  OrrNyan/OrrNyan/Resources/Lottie/LottieMainViewWalk.json
  OrrNyan/OrrNyan/Resources/Lottie/LottieMypageViewSleep.json
  OrrNyan/OrrNyan/Resources/Lottie/LottieMypageViewawake.json
  OrrNyan/OrrNyan/Resources/firstCat.json
Labels: style

#47 [Feat] #17 - SettingPopupView추가
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/UI/Components/AudioManager.swift
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
Labels: feat

#48 Feat/#37 - MainView to StageView transition Beautify
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Components/AppLifeCycleModifier.swift
  OrrNyan/OrrNyan/UI/Components/AudioManager.swift
  OrrNyan/OrrNyan/UI/Components/CatButtonStyle.swift
  OrrNyan/OrrNyan/UI/Components/LottieView.swift
  OrrNyan/OrrNyan/UI/Screen/ContentView.swift
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/LoginView.swift
  OrrNyan/OrrNyan/UI/Screen/LoginView_malty.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainTopView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
  OrrNyan/OrrNyan/UI/Screen/StageView.swift
  OrrNyan/OrrNyan/UI/Screen/TestTransitionView.swift
  OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
  OrrNyan/OrrNyan/ViewModels/StageViewModel.swift
Labels: feat

#50 Feat/#43 - LogIn
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Screen/ContentView.swift
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/LoginView.swift
  OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
  OrrNyan/OrrNyan/Utilities/Firebase/SignInWithApple.swift
  OrrNyan/OrrNyan/Utilities/Firebase/SignInWithGoogle.swift
Labels: feat, fix

#51 [Refactor] 메인뷰에서 element가 프레임 밖에서 안으로 들어오는 애니메이션 구현 부분 코드 수정했습니다.
  OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
Labels: refactor

#52 [Feat] #17 - SettingPopupView의 AudioManager 기능 수정
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/Resources/TestBGM.mp3
  OrrNyan/OrrNyan/Resources/TestMeow.wav
  OrrNyan/OrrNyan/UI/Components/AudioManager.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
Labels: feat

#54 Feat/#44 MyPageView 1차 작업 완료
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Models/UserBadge.swift
  OrrNyan/OrrNyan/UI/Screen/MyPageView.swift
Labels: feat

#55 [Style] #45 - 이미지 svg 처리 -> 빈공간 눌리지 않도록 / Asset 최신화 작업 완료
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg01.imageset/StageBg01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg02.imageset/StageBg02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageBg/StageBg03.imageset/StageBg03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_01.imageset/StageEm01_01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_02.imageset/StageEm01_02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_03.imageset/StageEm01_03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_04.imageset/StageEm01_04.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_05.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_05.imageset/Image.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_06.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm01/StageEm01_06.imageset/Image.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_01.imageset/StageEm02_01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_02.imageset/StageEm02_02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_03.imageset/StageEm02_03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_04.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_04.imageset/Image.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_05.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm02/StageEm02_05.imageset/Image.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_01.imageset/StageEm03_01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_02.imageset/StageEm03_02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_03.imageset/StageEm03_03.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_04.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageEm/StageEm03/StageEm03_04.imageset/Image.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt01.imageset/StageSt01.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt02.imageset/StageSt02.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/StageSt/StageSt03.imageset/StageSt03.png
  OrrNyan/OrrNyan/Resources/SvgOutline/StageStSvg01.swift
  OrrNyan/OrrNyan/Resources/SvgOutline/StageStSvg02.swift
  OrrNyan/OrrNyan/Resources/SvgOutline/StageStSvg03.swift
  OrrNyan/OrrNyan/Resources/SvgOutline/SvgViewExample.swift
Labels: style

#57 [Style] #45 - badge 이미지 추가
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Abled/Badge01_abled.imageset/Badge01_abled.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Abled/Badge01_abled.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Abled/Badge02_abled.imageset/Badge02_abled.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Abled/Badge02_abled.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Abled/Badge03_abled.imageset/Badge03_abled.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Abled/Badge03_abled.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Abled/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Enabled/Badge01_Disabled.imageset/Badge01_Disabled.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Enabled/Badge01_Disabled.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Enabled/Badge02_Disabled.imageset/Badge02_Disabled.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Enabled/Badge02_Disabled.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Enabled/Badge03_Disabled.imageset/Badge03_Disabled.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Enabled/Badge03_Disabled.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Enabled/Contents.json
Labels: style

#56 [Feat] #17 - SettingPopupView의 Local Notification 기능 추가
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Components/AudioManager.swift
  OrrNyan/OrrNyan/UI/Components/UserPushNotification.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
Labels: feat

#60 Feat/#58 - SVG overlay 완료
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
Labels: feat

#61 Feat/#40
  OrrNyan/OrrNyan/Resources/Assets.xcassets/이/Contents.json
  OrrNyan/OrrNyan/Resources/StageInfo.json
  OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
Labels: refactor

#65 Feat/#58 - 발바닥이랑 고양이랑
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Image/Image/paw.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Image/Image/paw.imageset/paw.png
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
Labels: feat

#68 Feat/#44 MyPageView / BadgePopupView 작업 완료
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Detail/Badge01_Detail.imageset/Badge01_Detail.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Detail/Badge01_Detail.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Detail/Badge02_Detail.imageset/Badge02_Detail.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Detail/Badge02_Detail.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Detail/Badge03_Detail.imageset/Badge03_Detail.png
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Detail/Badge03_Detail.imageset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Images/Badge/Detail/Contents.json
  OrrNyan/OrrNyan/UI/Screen/BadgePopupView.swift
  OrrNyan/OrrNyan/UI/Screen/MyPageView.swift
Labels: feat

#69 [Feat] #44 - 에러 수정
  OrrNyan/OrrNyan/UI/Screen/MyPageView.swift
Labels: feat

#70 Feat/#58 - Fixed Error
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/UI/Screen/StageView.swift
  OrrNyan/OrrNyan/ViewModels/StageViewModel.swift
Labels: fix

#72 Feat/#58 - 발바닥 찍기
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
Labels: feat

#74 Feat/#58 - 고양이 블러 조절
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
  OrrNyan/OrrNyan/ViewModels/StageViewModel.swift
Labels: feat

#73 [Feat] # 17 - SettingPopupVeiw - Notification Authorization 기능 수정
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Components/UserPushNotification.swift
  OrrNyan/OrrNyan/UI/Screen/SantaTestView.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
Labels: feat

#75 Feat/#44 BadgePopupView 디테일 작업 완료
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Screen/BadgePopupView.swift
Labels: feat

#77 feat/#44 - out of range error 잡아주기
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/UI/Screen/GetBadgeAnimation.swift
Labels: feat, fix

#78 Feat/#66 Animation, Parallax
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
  OrrNyan/OrrNyan/ViewModels/MotionManager.swift
Labels: feat

#79 [Feat] #17 - SettingPopupView 알림 권한 기능 수정_찐막
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Black/Black100.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Gray/Gray200.colorset/Contents.json
  OrrNyan/OrrNyan/UI/Components/UserPushNotification.swift
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/SantaTestView.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
Labels: feat

#84 Feat/#58
  OrrNyan/OrrNyan/Models/UserFloor.swift
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/UI/Components/ACarousel.swift
  OrrNyan/OrrNyan/UI/Screen/StageView.swift
  OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
Labels: feat

#86 [Chore] #85 - SettingPopupView의 Scene 전환 감지를 위한 코드 추가
  OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainTopView.swift
  OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
Labels: chore

#88 Feat/#58 - 깃발꽂기 기능 구현 완료
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/UI/Screen/Stage/ACarousel.swift
  OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
Labels: feat

#91 [Fix] #90 - AppleLoin 버그 수정
  OrrNyan/OrrNyan/Utilities/Firebase/SignInWithApple.swift
Labels: fix

#95 [Feat] #93 - 현재 층계값을 항상 가지고 있는 User.instance.userFloor 추가
  OrrNyan/OrrNyan Watch App/Utilities/StairTest.swift
  OrrNyan/OrrNyan/Models/User.swift
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/UI/Screen/ContentView.swift
Labels: feat

#101 MyPageView 데이터 처리
  OrrNyan/OrrNyan/UI/Screen/MyPage/BadgePopupView.swift
  OrrNyan/OrrNyan/UI/Screen/MyPage/MyPageView.swift
Labels: feat

#104 Feat/#99 - Firebase UserStage CRUD
  OrrNyan/OrrNyan/Models/User.swift
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
Labels: feat

#107 [Chore] #102 - Local Push Alert 내용 수정
  OrrNyan/OrrNyan/UI/Components/UserPushNotification.swift
Labels: chore

#113 Feat/#99 로그인시 바로 데이터 받아오는 로직 추가
  OrrNyan/OrrNyan/OrrNyanApp.swift
  OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
Labels: feat

#115 [Feat] #98 - WatchOS View 구현
  OrrNyan/OrrNyan Watch App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  OrrNyan/OrrNyan Watch App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  OrrNyan/OrrNyan Watch App/Resources/WatchLottie/Lottie_MainView_Walk.json
  OrrNyan/OrrNyan Watch App/Resources/WatchLottie/watchLottie.json
  OrrNyan/OrrNyan Watch App/UI/Components/LottieViewWatch.swift
  OrrNyan/OrrNyan Watch App/UI/Screen/ContentView.swift
  OrrNyan/OrrNyan Watch App/Utilities/StairTest.swift
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  OrrNyan/OrrNyan/Resources/Assets.xcassets/Colors/Purple/Purple300.colorset/Contents.json
  OrrNyan/OrrNyan/Resources/Lottie/WatchLottie.json
  OrrNyan/OrrNyan/UI/Components/UserPushNotification.swift
  OrrNyan/OrrNyan/UI/Screen/Login/CreateNameView.swift
Labels: feat

#119 [FEAT] #110 - 버그 수정 및 서버 업데이트 기능 적용
  OrrNyan/OrrNyan/Models/UserStage.swift
  OrrNyan/OrrNyan/UI/Screen/Stage/ACarousel.swift
  OrrNyan/OrrNyan/UI/Screen/Stage/StageView.swift
  OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
Labels: feat

#120 [Feat] #116 - FloorUpdatedAlert 뷰 기능구현, 유저 플로어 로직 일부 수정
  OrrNyan/OrrNyan.xcodeproj/project.pbxproj
  OrrNyan/OrrNyan/Models/User.swift
  OrrNyan/OrrNyan/OrrNyan.entitlements
  OrrNyan/OrrNyan/UI/Screen/Alert/FloorUpdatedAlert.swift
  OrrNyan/OrrNyan/UI/Screen/ContentView.swift
  OrrNyan/OrrNyan/UI/Screen/Login/CreateNameView.swift
  OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
  OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
Labels: feat
